from os import *
import sys
import platform


platform = platform.platform(terse=1)

if 'VERILATOR_ROOT' in environ: _VERILATOR =environ['VERILATOR_ROOT']
else: _VERILATOR ='/Users/patriciokaplan/Downloads/verilator-3.846'

libs = Split("boost_python")

if 'BOOST_INCLUDE' in environ: libpath=Split(environ['BOOST_INCLUDE']+'/stage/lib')
else: libpath=[]

includes = ["include","/usr/include/python2.7", _VERILATOR+'/include']

if 'BOOST_INCLUDE' in environ: includes.append(environ['BOOST_INCLUDE'])

if 'GEN_TREE' in environ: gen_tree=environ['GEN_TREE']
else: gen_tree = '/home/patricio/Documents/musings_gen'

gen_tree += '/' + platform + '/verilog/fifo'

verilator_obj_dir = gen_tree+'/obj_dir'
verilator_obj_dir_dump = gen_tree+'/obj_dir_dump'

def verilator_emitter (target, source, env):
	for s in source:
		p = verilator_obj_dir+'/V'+ str(s)[:-2]
		target = [ (p+x) for x in Split('.cpp .h __Syms.cpp __Syms.h') ]
	return target,source

def verilator_dump_emitter (target, source, env):
	for s in source:
		p = verilator_obj_dir_dump+'/V'+ str(s)[:-2]
		target = [ (p+x) for x in Split('.cpp .h __Syms.cpp __Syms.h __Trace.cpp __Trace__Slow.cpp') ]
	return target,source
	
verilator_dump_builder= Builder(action='verilator --Mdir '+verilator_obj_dir_dump+' --trace --cc $SOURCE', emitter=verilator_dump_emitter)

verilator_builder= Builder(action='verilator --Mdir '+verilator_obj_dir+' -O3 --cc $SOURCE', emitter=verilator_emitter)

if ARGUMENTS.get('dump',0): dump=1
else: dump=0


env = Environment(
                  CPPPATH = includes,
                  LIBS = libs,
                  LIBPATH = libpath,
                  FRAMEWORKS = Split("Python"),
                  SHLIBPREFIX = '',
                  SHLIBSUFFIX = '.dylib',
		  BUILDERS={'VerilatorDump':verilator_dump_builder, 'Verilator':verilator_builder},
		  SRC_TREE=getcwd(),
		  GEN_TREE=gen_tree,
		  VERILATOR=_VERILATOR,
		  DUMP=dump
                )

# copy dynamic libraries paths
for v in Split('DYLD_FALLBACK_LIBRARY_PATH LD_LIBRARY_PATH'): 
	if v in environ:
		env['ENV'][v]=environ[v]

Export('env')

Repository(env['VERILATOR'])

VariantDir(gen_tree, '.')

if dump: env.VerilatorDump('fifo.v')
else: env.Verilator('fifo.v')

env.SConscript(gen_tree+'/include/SConscript')
env.SConscript(gen_tree+'/src/SConscript')

env.SConscript('test1/SConscript')
